### ISSUE TITLE
TypeError: can't access property "click", this.currentVideovideo.querySelector(...) is null

### ISSUE THREAD

**Issue by scalp42** [Wilmox/LaterGator#1]
Hi @Wilmox 

Thanks for the script idea! Unfortunately, I just learned about the 5000 limit and there's no way to delete the actual playlist, so I've been trying a bunch of things.

I was excited by your script as it seems most of the ones out there delete one video at a time, which would take days.

When I try to run it (I made sure to switch from Dutch), I'm running into the following issue:

```
Uncaught (in promise) TypeError: can't access property "click", this.currentVideovideo.querySelector(...) is null
    deleteVideoFromWatchLater debugger eval code:23
    run debugger eval code:65
    async* debugger eval code:83
debugger eval code:23:32
    run debugger eval code:74
    InterpretGeneratorResume self-hosted:1455
    AsyncFunctionNext self-hosted:852
    (Async: async)
    <anonymous> debugger eval code:83
    getEvalResult resource://devtools/server/actors/webconsole/eval-with-debugger.js:238
    evalWithDebugger resource://devtools/server/actors/webconsole/eval-with-debugger.js:166
    evaluateJS resource://devtools/server/actors/webconsole.js:940
    evaluateJSAsync resource://devtools/server/actors/webconsole.js:846
    makeInfallible resource://devtools/shared/ThreadSafeDevToolsUtils.js:103
```

Any chance you have an idea?

Thank you a lot in advance 🇳🇱

**Comment by scalp42** [comment]
Ah, found the issue: `Action Menu` vs `Action menu`. I don't think it's batching also but not a big deal. Going to let it run for a while.

**Comment by Wilmox** [comment]
Hey @scalp42! 

Thanks for checking out my tool!

My bad for the typo in the README. So the fix is just the lowercase `m`?

Greetings
